### ISSUE TITLE
1-Reflex Bugs / Suggestions 

### ISSUE THREAD

**Issue by TheDiamondBlock** [Shawckz/ReflexIssues#1]
[Video Link w/ Bugs](https://www.youtube.com/watch?v=prwr5d9R4P0)

**Video Overview**
- Phase check enabled breaks the server, you must disable it to move.
- Speed false-positives when a player jumps and is knocked backward. (Or take enough KB?)
- When entering gamemode and leaving it while in the air, you will be checked for flying and if you **do not** move for the check time, you will be autobanned.
- Standing on slabs seem to activate constant fly inspections
- BHOP on some clients is undetectable on SPEED checks (others it works great, maybe depending on how fast you're actually going)

**Suggestions:**
- Lang for user's autoban message
- While player is being autobanned, they cannot hit other players (with FF you can continue to hit players through the glass)
- Nofall check

**Error?**
When a player is hit or breaks a block, a Null Pointer appears in console. [Hitting Player](http://prnt.sc/c12qki) | [Breaking Block](http://prnt.sc/c12vzf)

Enjoying this, I'll probably just disable the autoban feature from some checks for now. Still would like to see it functional with PvP.

**Comment by Shawckz** [comment]
Thanks, working on this now

**Comment by Shawckz** [comment]
Bugs should be fixed, new version will be available for download on website: 1.0.2-BETA
